{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.50",
   "distribution_type" : "module",
   "version" : "0.03",
   "name" : "EV-Loop-Async",
   "author" : [],
   "license" : "unknown",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "EV" : 3.7,
      "Async::Interrupt" : 0.5,
      "common::sense" : 0
   },
   "abstract" : null,
   "configure_requires" : {
      "EV" : 3.7,
      "ExtUtils::MakeMaker" : 0
   }
}
